;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
unalias=alias /d $1
vi=vim $*
..=cd ..
la=ls -a
cd..=cd ..
pdw=pwd
tcpp=.\a.exe < in.txt > out.txt
gs=git status
ga=git add
gb=git branch
gba=git branch -a
gbd=git branch -D
gcm=git commit -m
gco=git checkout
gcob=git checkout -b
gd=git diff
gp=git push
gpom=git pull origin main
cmderr=cd /d "%CMDER_ROOT%"